name: Releases
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - uses: bufbuild/buf-setup-action@v1.7.0
      - name: Ensure proto files are linted
        run: buf lint
      - name: Build server binary
        run: ./build.sh
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            benchmark-japan-vps.tar.gz
          token: ${{ secrets.RELEASE_TOKEN }}
